/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "npbyzgvsujrwlfhljgre"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wYnl6Z3ZzdWpyd2xmaGxqZ3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODczOTgsImV4cCI6MjA3ODM2MzM5OH0.G_8pv-DiNp1nqtsAvEYUfHRR8OvF25-ZwrFkWIoxruI"